config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  resources :users

  resources :contacts do
    post 'reply', on: :member
  end
  
  resources :videos, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

 # ścieżki główne dla różnych typów użytkowników
 authenticated :user, -> user { user.admin? } do
  resources :admins, only: [:users, :destroy, :all]
  root 'admins#index', as: :admin_root
end

authenticated :user, -> user { user.premium? } do
  root 'premium_users#index', as: :premium_root
end

authenticated :user do
  root 'standard_users#index', as: :authenticated_root
end


  root "main#index"


  #main
  get "ind", to: "main#index", as: "ind"
  get "log", to: "main#log", as: "log"
  get "help", to: "main#help", as: "help"
  get "reg", to: "main#reg", as: "reg"
  get "search_main", to: "main#search", as: "search_main"


  #admin
  get "aind", to: "admins#index", as: "aind"
  get "ahelp", to: "admins#help", as: "ahelp"
  get "usr", to: "admins#users", as: "usr"
  get "all", to: "admins#all", as: "all"
  get "rep", to: "admins#reports", as: "rep"
  get "set", to: "admins#settings", as: "set"
  get '/moon', to: 'admins#moon', as: 'moon'
  get '/sun', to: 'admins#sun', as: 'sun'

  #standard_user
  get "uind", to: "standard_users#index", as: "uind"
  get "prof", to: "standard_users#profile", as: "prof"
  get "prem", to: "standard_users#premium", as: "prem"
  get "adm", to: "standard_users#add_movie", as: "adm"
  get "uhelp", to: "standard_users#help", as: "uhelp"
  post 'uhelp', to: 'standard_users#new'

  #premium_user
  get "pind", to: "premium_users#index", as: "pind"
  get "profp", to: "premium_users#profile", as: "profp"
  get "add_premium", to: "premium_users#add", as: "add_premium"
  get "phelp", to: "premium_users#help", as: "phelp"
  post 'phelp', to: 'premium_users#new'


  get "profil", to: "users#profile", as: "profile"

  get "test", to: "videos#new_premium", as: "test"
  #search functionality routes
  get 'search', to: 'search#index'

  resources :users, only: [:show] do
    member do
      get 'profile'
    end
  end

  get 'userp/:id', to: 'users#profile', as: 'userp'


  get 'videos/:id/download', to: 'videos#download', as: 'download_video'
  
  get 'new_standard_video', to: 'videos#new_standard', as: 'new_standard_video'

  get 'new_premium_video', to: 'videos#new_premium', as: 'new_premium_video'

end

app/views/admins/all.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= aind_path %>">Panel główny</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= usr_path %>">Użytkownicy</a>
    </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filmy
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= all_path %>">Wszystkie filmy</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= rep_path %>">Zgłoszone filmy</a></li>
        </ul>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= ahelp_path %>">Strefa pomocy</a>
    </li>
      <li class="nav-item">
      <a class="nav-link active" href="<%= set_path %>">Ustawienia strony</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">
      Wyloguj
      </a>
      </li>
    </ul>
  </div>
  <%= search_form_for @users_search, url: search_path, method: :get, html: { class: "d-flex", role: "search", style: "float:right" } do |f| %>
    <%= f.text_field :name_cont, placeholder: "Wyszukaj użytkowników...", class: "form-control me-2", type: "search", aria: { label: "Szukaj" }, style:"width:250px;" %>
    <%= f.submit "Szukaj", class: "btn", style: "background-color: #ff69b4;" do %>
      <b>Szukaj</b>
    <% end %>
  <% end %>
</div>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <center>
            <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
            <% end %>
      </center>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div id="cont" style="margin-top:100px; margin-bottom:100px" class="page-transition">

<center><h2 style="font-weight:700; color: #430f58; margin-bottom:20px;">Zarządzaj wszystkimi filmami 🎥</h2>

<hr style="border: 2px solid; color: #ff69b4; margin-left:0px; width:90%"></center>

<div style="width:40%; float:left; margin-bottom:30px; margin-left:150px">
W tej sekcji możesz przeglądać wszystkie filmy przesłane przez użytkowników. Oprócz tego masz pełny dostęp do komentarzy pod każdym filmem. Jeśli zauważysz nieodpowiednie treści, możesz je łatwo usunąć, dbając o bezpieczeństwo i jakość naszej społeczności.
</div>
<div style="width:40%; float:left; margin-bottom:30px; margin-left:50px">

<ul style="margin-top:30px">
<li style="color:#f70776; font-size:18px"><span style="color: black"><b>Przeglądaj i zarządzaj wszystkimi filmami</b></span></li>
<li style="color:#f70776; font-size:18px"><span style="color: black"><b>Monitoruj komentarze i usuwaj te, które łamią zasady</b></span></li>
</ul>

</div>
<center>
<hr style="border: 2px solid; color: #ff69b4; margin-left:0px; width:70%; margin-bottom:30px">
<div class="row" style="width:80%">
  <% @videos.each do |video| %>
    <div class="col-md-4 mb-4">
      <div class="card" style="border: 2px solid #F433FF; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);  background-color: #ffcde3;">
        <div class="card-body">
          <h5 class="card-title"><%= video.title %></h5>
          <p><%= video.description %></p>
          <video width="80%" controls style="border-radius:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
            <source src="<%= rails_blob_path(video.uploaded_video, only_path: true) %>" type="video/mp4">
            Twoja przeglądarka nie wspiera elementu wideo.
          </video>
          <p class="card-text">
            <span class="badge rounded-pill" style="background-color:#5a005a; font-size:15px">Twórca: <strong><%= video.user.name %></strong></span><br>
            <span class="badge rounded-pill" style="background-color:#5a005a; font-size:13px">Data wstawienia: <strong><%= video.created_at.strftime("%Y-%m-%d %H:%M:%S") %></strong></span><br>
          </p>
          <%= link_to 'Komentarze', video_path(video), class: 'btn', style: 'color:#5a005a; border:1px solid #5a005a' %>
        </div>
      </div>
    </div>
  <% end %>
</div>



</center>
</div>
<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

app/views/admins/help.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= aind_path %>">Panel główny</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= usr_path %>">Użytkownicy</a>
    </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filmy
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= all_path %>">Wszystkie filmy</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= rep_path %>">Zgłoszenia</a></li>
        </ul>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= ahelp_path %>">Strefa pomocy</a>
    </li>
      <li class="nav-item">
      <a class="nav-link active" href="<%= set_path %>">Ustawienia strony</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">
      Wyloguj
      </a>
      </li>
    </ul>
  </div>
  <%= search_form_for @users_search, url: search_path, method: :get, html: { class: "d-flex", role: "search", style: "float:right" } do |f| %>
    <%= f.text_field :name_cont, placeholder: "Wyszukaj użytkowników...", class: "form-control me-2", type: "search", aria: { label: "Szukaj" }, style:"width:250px;" %>
    <%= f.submit "Szukaj", class: "btn", style: "background-color: #ff69b4;" do %>
      <b>Szukaj</b>
    <% end %>
  <% end %>
</div>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <center>
            <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
            <% end %>
      </center>
      </div>
    </div>
  </div>
</div>





<div id="cont" style="margin-top:80px; margin-bottom:300px" class="page-transition">
<div style="width:100%; height:auto; margin-bottom:100px; height:550px">
<center><h2 style="font-weight:700; color: #430f58;">Bieżące problemy użytkowników</h2>

<span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Kliknij na ikonkę, aby dowiedzieć się więcej!">
<button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal1">
   <%= image_tag("question_mark.jfif", height: 100, style:"border-radius:30px") %>
</button>
</span>

<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="text-align:justify">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header" style="border-bottom: 0.5px solid black;">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Zarządzanie zapytaniami użytkowników</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        W tej zakładce możesz przeglądać zapytania i problemy zgłoszone przez użytkowników oraz odpowiadać na nie. 
        <p style="margin-top:10px"><b>Co możesz zrobić w tej sekcji:</b></p>
        <i class="fas fa-check"></i> <b>Odpowiadanie na Zapytania</b> - Odpowiedz na pytania użytkowników bezpośrednio w systemie.<br>
        <i class="fas fa-check"></i> <b>Przeglądanie Szczegółów</b> - Sprawdź szczegóły zgłoszeń, aby lepiej zrozumieć problemy użytkowników.

        <center>
          <p style="color:#AA336A; font-size:20px; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1); margin-top:20px">
            <b><i>Zespół ClipCentral </i>📷</b>
          </p>
        </center>
      </div>
      <div class="modal-footer" style="border-top:0.5px solid #333">
        <button type="button" class="btn" data-bs-dismiss="modal" style="background-color:#ff69b4;">Zamknij</button>
      </div>
    </div>
  </div>
</div>


<br>

<table class="table table-sm table-info" style="width:80%; margin-top:30px; box-shadow: 2px 2px 20px #333; margin-bottom:200px;">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">E-mail</th>
      <th scope="col">Wiadomość</th>
      <th scope="col">Utworzono</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each_with_index do |contact, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td style="width:30px"><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td style="width:170px"><%= contact.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td style="width:50px">
          <% if contact.reply.present? %>
            <span>✅</span>
          <% else %>
            <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#replyModal-<%= index %>" style="margin-bottom:10px">
              Odpisz
            </button>
          <% end %>
          
          <%= form_with model: contact, method: :delete, local: true do %>
            <%= submit_tag 'Usuń', class: 'btn btn-outline-danger', data: { confirm: 'Czy na pewno chcesz usunąć ten kontakt?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<% @contacts.each_with_index do |contact, index| %>
    <div class="modal fade" id="replyModal-<%= index %>" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel-<%= index %>" aria-hidden="true" style="text-align: justify;">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="background-color: #ffcde3;">
          <div class="modal-header" style="border-bottom: 0.5px solid black;">
            <h1 class="modal-title fs-5" id="replyModalLabel-<%= index %>">Odpowiedz na wiadomość</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <% if contact.reply.present? %>
              <p>Na tę wiadomość już odpowiedziano.</p>
            <% else %>
              W tej sekcji możesz odpowiedzieć na wiadomość od użytkownika. Proszę podaj swoją odpowiedź poniżej.
              <%= form_with url: reply_contact_path(contact), method: :post, local: true do |form| %>
                <div class="form-group" style="margin-top: 10px;">
                  <%= form.label :reply, "Odpowiedź", style:"font-weight:600" %>
                  <%= form.text_area :reply, class: "form-control" %>
                </div>
                <%= form.submit "Wyślij", class: "btn", style:"background-color: #ff69b4; margin-top:15px" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
  


</center>
</div>
</div>
<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

app/views/admins/reports.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= aind_path %>">Panel główny</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= usr_path %>">Użytkownicy</a>
    </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filmy
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= all_path %>">Wszystkie filmy</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= rep_path %>">Zgłoszenia</a></li>
        </ul>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= ahelp_path %>">Strefa pomocy</a>
    </li>
      <li class="nav-item">
      <a class="nav-link active" href="<%= set_path %>">Ustawienia strony</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">
      Wyloguj
      </a>
      </li>
    </ul>
  </div>
  <%= search_form_for @users_search, url: search_path, method: :get, html: { class: "d-flex", role: "search", style: "float:right" } do |f| %>
    <%= f.text_field :name_cont, placeholder: "Wyszukaj użytkowników...", class: "form-control me-2", type: "search", aria: { label: "Szukaj" }, style:"width:250px;" %>
    <%= f.submit "Szukaj", class: "btn", style: "background-color: #ff69b4;" do %>
      <b>Szukaj</b>
    <% end %>
  <% end %>
</div>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <center>
            <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
            <% end %>
      </center>
      </div>
    </div>
  </div>
</div>



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div id="cont" style="margin-top:80px; margin-bottom:100px" class="page-transition">

<center><h2 style="font-weight:700; color: #430f58;">Zgłoszone filmy</h2>

<hr style="border: 2px solid; color: #ff69b4; margin-left:0px; width:90%">

</center>

<div style="width:40%; float:left; margin-bottom:30px; margin-left:150px">
Na tej stronie możesz przeglądać filmy zgłoszone przez użytkowników, zarządzać zgłoszeniami i podjąć odpowiednie działania. Możesz zobaczyć szczegóły każdego zgłoszenia, w tym użytkownika, który je zgłosił oraz powód zgłoszenia. To Ty decydujesz, czy zgłoszony film powinien zostać usunięty!</div>
<div style="width:40%; float:left; margin-bottom:30px; margin-left:50px">

<ul style="margin-top:30px">
<li style="color:#f70776; font-size:18px"><span style="color: black"><b>Przeglądaj i zarządzaj wszystkimi filmami</b></span></li>
<li style="color:#f70776; font-size:18px"><span style="color: black"><b>Monitoruj komentarze i usuwaj te, które łamią zasady</b></span></li>
</ul>

</div>


<center>
<hr style="border: 2px solid; color: #ff69b4; margin-left:0px; width:90%">
<div class="row" style="width:80%;">
  <% @reports.each do |report| %>
    <div class="col-md-4 mb-4">
      <div class="card" style="border: 2px solid #F433FF; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);  background-color: #ffcde3; height:750px">
        <div class="card-body">
          <h5 class="card-title"><span class="badge rounded-pill" style="background-color:#5a005a; font-size:20px"><%= report.video.title %></span></h5>
          <video width="80%" controls style="border-radius:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
            <source src="<%= rails_blob_path(report.video.uploaded_video, only_path: true) %>" type="video/mp4">
            Twoja przeglądarka nie wspiera elementu wideo.
          </video>
          <p class="card-text">
          <ul class="list-group" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); border: 0.5px solid #F433FF; ">
            <li class="list-group-item" style="background-color:#C2DFFF; border: 0.5px solid #F433FF"><b>Powód</b>: <%= report.reason %></li>
            <li class="list-group-item" style="background-color:#C2DFFF; border: 0.5px solid #F433FF"><b>Zgłoszony przez</b>: <%= report.user.name %></li>
          </ul>
          </p>
          <%= link_to 'Zarządzaj filmem', video_path(report.video), class: 'btn', style: 'color:#5a005a; border:1px solid #5a005a' %>
        </div>
      </div>
    </div>
  <% end %>
</div>





</center>
</div>
<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

app/views/admins/settings.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= aind_path %>">Panel główny</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= usr_path %>">Użytkownicy</a>
    </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filmy
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= all_path %>">Wszystkie filmy</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= rep_path %>">Zgłoszenia</a></li>
        </ul>
      </li>
      <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="<%= ahelp_path %>">Strefa pomocy</a>
    </li>
      <li class="nav-item">
      <a class="nav-link active" href="<%= set_path %>">Ustawienia strony</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">
      Wyloguj
      </a>
      </li>
    </ul>
  </div>
  <%= search_form_for @users_search, url: search_path, method: :get, html: { class: "d-flex", role: "search", style: "float:right" } do |f| %>
    <%= f.text_field :name_cont, placeholder: "Wyszukaj użytkowników...", class: "form-control me-2", type: "search", aria: { label: "Szukaj" }, style:"width:250px;" %>
    <%= f.submit "Szukaj", class: "btn", style: "background-color: #ff69b4;" do %>
      <b>Szukaj</b>
    <% end %>
  <% end %>
</div>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <center>
            <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
            <% end %>
      </center>
      </div>
    </div>
  </div>
</div>


<div id="cont" style="margin-top:80px" class="page-transition">
<div style="width:30%; float:left; margin: 50px; margin-left:100px; height:550px">
<h1 class="badge text" style="background-color:#ff69b4; margin-top:30px; margin-bottom:20px; font-size:30px; box-shadow: 2px 2px 20px #333; margin:10px">Ustawienia strony ⚙️</h1>
<p style="margin-top:50px; font-size:18px">
Jako Administrator masz możliwość personalizacji wyglądu naszej strony! Do wyboru są dwa estetyczne tryby:
<ul style="font-size:18px">
    <li>☀️ Tryb jasny - domyślny styl w odcieniach różu, fioletu i błękitu.</li>
    <li>🌙 Tryb ciemny - elegancka kompozycja szarości z subtelnymi akcentami różu.</li>
</ul>
<span style="font-size:18px">Możesz zmieniać te ustawienia w dowolnym momencie. Pamiętaj, że Twoje wybory będą widoczne dla wszystkich użytkowników strony, wpływając na ich ogólne doświadczenie.
</span></p>
</div>

<div style="width:50%; float:left; margin-top:50px; margin-left:100px; margin-bottom:20px; height:550px">
<center>
<%= image_tag("setting.jpeg", height: 400, class:"logo", style:"margin-bottom:30px") %>

<% if cookies[:moon] %>
<%= button_to 'Przejdź do trybu jasnego!', sun_path, method: :get, class: 'btn', style: 'background-color:#C2DFFF; box-shadow: 2px 2px 20px #333; font-size:25px'%>
<% else %>
<%= button_to 'Przejdź do trybu ciemnego!', moon_path, method: :get, class: 'btn', style: 'background-color:#C2DFFF; box-shadow: 2px 2px 20px #333; font-size:25px;'%>
<% end %>
</center>
</div>





</div>
<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>