config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  resources :users

  resources :contacts do
    post 'reply', on: :member
  end
  
  resources :videos, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

 # ścieżki główne dla różnych typów użytkowników
 authenticated :user, -> user { user.admin? } do
  resources :admins, only: [:users, :destroy, :all]
  root 'admins#index', as: :admin_root
end

authenticated :user, -> user { user.premium? } do
  root 'premium_users#index', as: :premium_root
end

authenticated :user do
  root 'standard_users#index', as: :authenticated_root
end


  root "main#index"


  #main
  get "ind", to: "main#index", as: "ind"
  get "log", to: "main#log", as: "log"
  get "help", to: "main#help", as: "help"
  get "reg", to: "main#reg", as: "reg"
  get "search_main", to: "main#search", as: "search_main"


  #admin
  get "aind", to: "admins#index", as: "aind"
  get "ahelp", to: "admins#help", as: "ahelp"
  get "usr", to: "admins#users", as: "usr"
  get "all", to: "admins#all", as: "all"
  get "rep", to: "admins#reports", as: "rep"
  get "set", to: "admins#settings", as: "set"
  get '/moon', to: 'admins#moon', as: 'moon'
  get '/sun', to: 'admins#sun', as: 'sun'

  #standard_user
  get "uind", to: "standard_users#index", as: "uind"
  get "prof", to: "standard_users#profile", as: "prof"
  get "prem", to: "standard_users#premium", as: "prem"
  get "adm", to: "standard_users#add_movie", as: "adm"
  get "uhelp", to: "standard_users#help", as: "uhelp"
  post 'uhelp', to: 'standard_users#new'

  #premium_user
  get "pind", to: "premium_users#index", as: "pind"
  get "profp", to: "premium_users#profile", as: "profp"
  get "add_premium", to: "premium_users#add", as: "add_premium"
  get "phelp", to: "premium_users#help", as: "phelp"
  post 'phelp', to: 'premium_users#new'


  get "profil", to: "users#profile", as: "profile"

  get "test", to: "videos#new_premium", as: "test"
  #search functionality routes
  get 'search', to: 'search#index'

  resources :users, only: [:show] do
    member do
      get 'profile'
    end
  end

  get 'userp/:id', to: 'users#profile', as: 'userp'


  get 'videos/:id/download', to: 'videos#download', as: 'download_video'
  
  get 'new_standard_video', to: 'videos#new_standard', as: 'new_standard_video'

  get 'new_premium_video', to: 'videos#new_premium', as: 'new_premium_video'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @users_search = User.ransack(params[:q])
    
        Rails.logger.debug "User Search: #{@users_search.inspect}"
      
        @standard_users = @users_search.result.where(role: 0)
        @premium_users = @users_search.result.where(role: 1)
      end

    def profiles
        @user = User.find_by(name: params[:name]) # Assuming you pass user ID in the URL
    end
  end
  

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
  </div>
  <%= link_to "↩ Wróć do poprzedniej strony", "javascript:history.back()", class: "btn", style: "background-color: #ff69b4;" %>
</div>
</nav>


<div id="cont" style="margin-top:30px; height:1500px" class="page-transition">
  <center>
    <span class="badge text" style="background-color:#ff69b4; margin-top:60px; font-size:30px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);">Wyniki wyszukiwania 🔎</span>
  </center>

  <div style="width:40%; float:left; margin: 50px; height:auto; margin-bottom:30px; height:600px;">
    <center>
      <h3 style="font-weight:700; color: #430f58; border:2px solid #430f58; border-radius:100px; padding:5px">Użytkownicy Standardowi ⭐</h3>
      <div class="row">
        <% if @standard_users.any? %>
          <% @standard_users.each do |user| %>
            <div class="card" style="width: 19rem; margin: 50px; margin-left:150px; background-color: #ff77ab; border: 3px solid #ff0080; padding: 15px; margin-bottom: 15px; border-radius: 8px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);">
            <%= image_tag(user.avatar, alt: "Logo", height: 250, class:"logo") %>
              <div class="card-body">
                <h5 class="card-title"><%= user.name %></h5>
                <p class="card-text">Liczba filmów: <%= user.videos.count %></p>
                <%= link_to 'Profil', userp_path(user.id), class: 'btn btn-light', style: 'background-color: #fafafa; border:2px solid #333'%>
                                  <% if current_user.admin? %>
                        <%= button_to 'Usuń', admin_path(user), method: :delete, onclick: 'return confirmDelete()', class: 'btn btn-danger', style:'margin-top:10px' %>
                    <% end %>
                </div>
            </div>
          <% end %>
        <% else %>
          <p style="color: #333; font-size:25px; margin-top:30px">Brak użytkowników o podanej nazwie.</p>
        <% end %>
      </div>
    </center>
  </div>

  <div style="width:40%; float:left; margin: 50px; height:auto; margin-bottom:30px; height:600px; margin-left:140px">
    <center>
      <h3 style="font-weight:700; color: #430f58; border:2px solid #430f58; border-radius:100px; padding:5px">Użytkownicy Premium 🌟</h3>
      <div class="row">
        <% if @premium_users.any? %>
          <% @premium_users.each do |user| %>
            <div class="card" style="width: 19rem; margin: 50px; margin-left:160px;  background-color: #ff77ab; border: 3px solid #ff0080; padding: 15px; margin-bottom: 15px; border-radius: 8px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);">
              <%= image_tag(user.avatar, alt: "Logo", height: 250, class:"logo") %>
              <div class="card-body">
                <h5 class="card-title"><%= user.name %></h5>
                <p class="card-text">Liczba filmów: <%= user.videos.count %></p>
                <%= link_to 'Profil', userp_path(user.id), class: 'btn btn-light', style: 'background-color: #fafafa; border:2px solid #333' %>
                    <% if current_user.admin? %>
                        <%= button_to 'Usuń', admin_path(user), method: :delete, onclick: 'return confirmDelete()', class: 'btn btn-danger', style:'margin-top:10px' %>
                    <% end %>
                </div>
            </div>
          <% end %>
        <% else %>
          <p style="color: #333; font-size:25px; margin-top:30px">Brak użytkowników o podanej nazwie.</p>
        <% end %>
      </div>
    </center>
  </div>
</div>


<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

app/views/search/profiles.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
      <%= image_tag("navbar.png", alt: "Logo", width: 40, height: 40) %>
      <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= uind_path %>">Strona główna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= prof_path %>">Mój profil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= adm_path %>">Prześlij film</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= prem_path %>">Premium</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= uhelp_path %>">Pomoc</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">Wyloguj</a>
        </li>
      </ul>
    </div>
    <form class="d-flex" role="search" style="float:right">
      <input class="form-control me-2" type="search" placeholder="Wyszukaj na stronie..." aria-label="Szukaj">
      <button class="btn" style="background-color: #ff69b4" type="submit"><b>Szukaj</b></button>
    </form>
  </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <center>
          <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style: "background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>
          <% end %>
        </center>
      </div>
    </div>
  </div>
</div>

<div id="cont" style="margin-top:80px;" class="page-transition">
  <div style="width:30%; float:left; margin: 50px; height:auto;">
    <center>
      <div class="card" style="width: 18rem; margin-bottom:100px; box-shadow: 2px 2px 20px #333; background-color:#ffcde3; border: 2px solid #FF10F0; border-radius:10px">
        <% if @user.avatar.attached? %>
          <%= image_tag(@user.avatar, alt: "Logo", height: 280, class: "logo") %>
        <% else %>
          <%= image_tag("avatar.jpeg", alt: "Logo", height: 280, class: "logo") %>
        <% end %>

        <div class="card-body">
          <h5 class="card-title"><span class="badge rounded-pill" style="background-color:#ff69b4; font-size:20px; margin:5px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Profil Użytkownika</span></h5>
          <p class="card-text">Nazwa użytkownika: <strong><%= @user.name %></strong></p>
          <p class="card-text">Email: <strong><%= @user.email %></strong></p>
          <p class="card-text">Konto utworzone: <strong><%= @user.created_at.strftime("%Y-%m-%d") %></strong></p>
          <p class="card-text">Ostatnia aktualizacja: <strong><%= @user.updated_at.strftime("%Y-%m-%d") %></strong></p>
          <p class="card-text">Typ konta: <strong><%= @user.premium? ? "Premium" : "Standard" %></strong></p>
        </div>
      </div>
    </center>
  </div>

  <div style="width:50%; float:left; margin: 50px; height:auto; background-color:#C2DFFF; border-radius:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
    <center><h2 style="font-weight:700; color: #430f58; margin-top:20px">Filmy użytkownika 🎬</h2></center>
    <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">

    <% if @user.videos.any? %>
      <div class="row" style="width:100%; margin-top:50px">
        <% @user.videos.each do |video| %>
          <div class="card" style="border: 3px solid #F433FF; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); background-color: #ffcde3; width:45%; margin-right:5px; margin-left:31px; margin-top:20px; margin-bottom:20px">
            <div class="card-body">
              <center>
                <h5 class="card-title"><%= video.title %></h5>
                <p><%= video.description %></p>
                <video width="80%" controls style="border-radius:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
                  <source src="<%= rails_blob_path(video.uploaded_video, only_path: true) %>" type="video/mp4">
                  Twoja przeglądarka nie wspiera elementu wideo.
                </video>
                <p class="card-text">
                  <span class="badge rounded-pill" style="background-color:#5a005a; font-size:15px">Twórca: <strong><%= video.user.name %></strong></span><br>
                  <span class="badge rounded-pill" style="background-color:#5a005a; font-size:13px">Data wstawienia: <strong><%= video.created_at.strftime("%Y-%m-%d %H:%M:%S") %></strong></span><br>
                </p>
              </center>
            </div>
          </div>
        <% end %>
      </div>
    <% else %> 
      <p> <center>Ten użytkownik nie ma jeszcze żadnych filmów.</center></p>
    <% end %>
  </div>
</div>

<footer>
  <p><b>Copyright &copy; 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

<script>
  document.getElementById('user_avatar').addEventListener('change', function(event) {
    const fileNameElement = document.getElementById('file-name');
    const fileName = event.target.files.length ? event.target.files[0].name : 'Nie wybrano pliku';
    fileNameElement.textContent = fileName;
  });
</script>