config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  resources :users

  resources :contacts do
    post 'reply', on: :member
  end
  
  resources :videos, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:create, :destroy]
  end

 # ścieżki główne dla różnych typów użytkowników
 authenticated :user, -> user { user.admin? } do
  resources :admins, only: [:users, :destroy, :all]
  root 'admins#index', as: :admin_root
end

authenticated :user, -> user { user.premium? } do
  root 'premium_users#index', as: :premium_root
end

authenticated :user do
  root 'standard_users#index', as: :authenticated_root
end


  root "main#index"


  #main
  get "ind", to: "main#index", as: "ind"
  get "log", to: "main#log", as: "log"
  get "help", to: "main#help", as: "help"
  get "reg", to: "main#reg", as: "reg"
  get "search_main", to: "main#search", as: "search_main"


  #admin
  get "aind", to: "admins#index", as: "aind"
  get "ahelp", to: "admins#help", as: "ahelp"
  get "usr", to: "admins#users", as: "usr"
  get "all", to: "admins#all", as: "all"
  get "rep", to: "admins#reports", as: "rep"
  get "set", to: "admins#settings", as: "set"
  get '/moon', to: 'admins#moon', as: 'moon'
  get '/sun', to: 'admins#sun', as: 'sun'

  #standard_user
  get "uind", to: "standard_users#index", as: "uind"
  get "prof", to: "standard_users#profile", as: "prof"
  get "prem", to: "standard_users#premium", as: "prem"
  get "adm", to: "standard_users#add_movie", as: "adm"
  get "uhelp", to: "standard_users#help", as: "uhelp"
  post 'uhelp', to: 'standard_users#new'

  #premium_user
  get "pind", to: "premium_users#index", as: "pind"
  get "profp", to: "premium_users#profile", as: "profp"
  get "add_premium", to: "premium_users#add", as: "add_premium"
  get "phelp", to: "premium_users#help", as: "phelp"
  post 'phelp', to: 'premium_users#new'


  get "profil", to: "users#profile", as: "profile"

  get "test", to: "videos#new_premium", as: "test"
  #search functionality routes
  get 'search', to: 'search#index'

  resources :users, only: [:show] do
    member do
      get 'profile'
    end
  end

  get 'userp/:id', to: 'users#profile', as: 'userp'


  get 'videos/:id/download', to: 'videos#download', as: 'download_video'
  
  get 'new_standard_video', to: 'videos#new_standard', as: 'new_standard_video'

  get 'new_premium_video', to: 'videos#new_premium', as: 'new_premium_video'

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  has_one_attached :uploaded_video

  validates :title, presence: true
  validates :uploaded_video, presence: true
  validate :acceptable_video

  def acceptable_video
    return unless uploaded_video.attached?

    unless uploaded_video.byte_size <= 1.gigabyte
      errors.add(:uploaded_video, "is too big")
    end

    acceptable_types = ["video/mp4", "video/mpeg", "video/quicktime"]
    unless acceptable_types.include?(uploaded_video.content_type)
      errors.add(:uploaded_video, "must be a MP4, MPEG or MOV")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  def show
    @video = Video.find(params[:id])
    @comments = @video.comments.includes(:user)
    @comment = Comment.new
    @report = Report.new
  end

  def create
    @video = current_user.videos.build(video_params)

    if @video.save
      flash[:notice] = 'Film został pomyślnie przesłany.'
    if current_user.premium?
      redirect_to new_premium_video_path
    else
      redirect_to new_standard_video_path
    end

    else
    flash.now[:alert] = 'Wystąpił problem podczas przesyłania filmu.'
    
    if current_user.premium?
      redirect_to new_premium_video_path 
    else
      redirect_to new_standard_video_path
    end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    if current_user.admin?
      if @video.destroy
        flash[:success] = 'Film został usunięty pomyślnie.'
        redirect_to rep_path
      else
        flash[:error] = 'Wystąpił błąd podczas usuwania filmu.'
        redirect_to video_path(@video)
      end
    else
      flash[:alert] = 'Nie masz uprawnień do usunięcia tego filmu.'
      redirect_to video_path(@video)
    end
  end


  def download
    @video = Video.find(params[:id])
  
    if @video.uploaded_video.attached?
      mime_type = @video.uploaded_video.content_type
  
      send_data @video.uploaded_video.download, type: mime_type, disposition: 'attachment', filename: @video.uploaded_video.filename.to_s
    else
      render plain: "Nie znaleziono pliku", status: :not_found
    end
  end
  

  private

  def video_params
    params.require(:video).permit(:title, :description, :uploaded_video)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/new_premium.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= pind_path %>">Strona główna</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="<%= profp_path %>">Mój profil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="<%= add_premium_path %>">Prześlij film</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="<%= phelp_path %>">Pomoc</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">
      Wyloguj
      </a>
      </li>
      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown link
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>--!>
    </ul>
  </div>
</div>
</nav>


<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <center>
            <% if user_signed_in? %>
            <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
            <% end %>
      </center>
      </div>
    </div>
  </div>
</div>





<div id="cont" style="margin-top:80px" class="page-transition">

<div style="width:45%; float:left; margin: 50px; height:auto; margin-bottom:100px; margin-top:10px">
<center>
<h2 style="font-weight:700; color: #430f58;">Dodaj nowy film 🎬</h2></center>
<p style="margin-top:30px; font-size:18px">
Podziel się swoją twórczością z naszą społecznością! Wypełnij poniższe pola, aby dodać nowy film do ClipCentral. Upewnij się, że tytuł i opis dobrze oddają to, co chcesz przekazać.
</p>
<p class="badge rounded-pill" style="background-color:#ff69b4; font-size:15px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Obsługiwane formaty wideo: MP4, MPEG oraz MOV
</p>


<div class="card mb-3" style="width:80%; border: 2px solid #F433FF; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);  background-color: #ffcde3; margin-left:60px;">
  <div class="card-header">Podziel się tym, co dla Ciebie ważne! ✨</div>
  <div class="card-body">
  <%= form_with(model: @video, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title, "Tytuł" %>
      <%= form.text_field :title, class: 'form-control', required: true %>
      <div id="emailHelp" class="form-text">Wpisz chwytliwy tytuł, który przyciągnie uwagę widzów.</div>
    </div>
  
    <div class="form-group">
      <%= form.label :description, "Opis filmu" %>
      <%= form.text_area :description, class: 'form-control', rows: 2, required: true %>
      <div id="emailHelp" class="form-text">Opisz, o czym jest Twój film. Dodaj wszelkie informacje, które mogą zainteresować widzów i zachęcić ich do obejrzenia.</div>
    </div>
  
    <div class="form-group" style="margin-top:10px">
    <%= form.label :uploaded_video, "Wybierz plik", class: "btn", style: "background-color:#5a005a; color:white; box-shadow: 0 10px 30px #FF33AA;", for: 'videoFile' %>
    <%= form.file_field :uploaded_video, required: true, id: 'videoFile', class: 'form-control-file', style: 'display:none' %>
    <span id="file-name" style="margin-left: 10px;">Nie wybrano pliku</span>
  </div>
  
    <%= form.submit 'Wyślij', class: 'btn', style: 'margin-top:10px; background-color:#c94bc9; font-size:20px;' %>
  <% end %> 
  
</div>
</div>

</div>

<div style="width:40%; float:left; margin: 50px; height: auto; margin-bottom:100px; margin-top:80px; margin-left:70px">

<%= image_tag("add_movie.jpeg", height: 500, class:"logo", style: "margin-left:30px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);") %>

</div>

</div>
<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

<script>
  document.getElementById('videoFile').addEventListener('change', function(event) {
    const fileNameElement = document.getElementById('file-name');
    const fileName = event.target.files.length ? event.target.files[0].name : 'Nie wybrano pliku';
    fileNameElement.textContent = fileName;
  });
</script>

app/views/videos/new_standard.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
      <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
      <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= uind_path %>">Strona główna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= prof_path %>">Mój profil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= adm_path %>">Prześlij film</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= prem_path %>">Premium</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= uhelp_path %>">Pomoc</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#"  data-bs-toggle="modal" data-bs-target="#exampleModal">Wyloguj</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="background-color: #ffcde3;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Czy na pewno chcesz się wylogować?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <center>
          <% if user_signed_in? %>
          <%= button_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn', style:"background-color:#c94bc9; font-size:20px", data: { confirm: "Czy na pewno chcesz się wylogować?" } %>        
          <% end %>
        </center>
      </div>
    </div>
  </div>
</div>

<div id="cont" style="margin-top:80px" class="page-transition">
  <div style="width:45%; float:left; margin: 50px; height:auto; margin-bottom:100px; margin-top:10px">
    <center>
      <h2 style="font-weight:700; color: #430f58;">Dodaj nowy film 🎬</h2>
    </center>
    <p style="margin-top:30px; font-size:18px">
      Podziel się swoją twórczością z naszą społecznością! Wypełnij poniższe pola, aby dodać nowy film do ClipCentral. Upewnij się, że tytuł i opis dobrze oddają to, co chcesz przekazać.
    </p>
    <p class="badge rounded-pill" style="background-color:#ff69b4; font-size:15px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Obsługiwane formaty wideo: MP4, MPEG oraz MOV</p>

    <div class="card mb-3" style="width:80%; border: 2px solid #F433FF; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);  background-color: #ffcde3; margin-left:60px;">
      <div class="card-header">Podziel się tym, co dla Ciebie ważne! ✨</div>
      <div class="card-body">
        <%= form_with(model: @video, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :title, "Tytuł" %>
          <%= form.text_field :title, class: 'form-control', required: true %>
          <div id="emailHelp" class="form-text">Wpisz chwytliwy tytuł, który przyciągnie uwagę widzów.</div>
        </div>
      
        <div class="form-group">
          <%= form.label :description, "Opis filmu" %>
          <%= form.text_area :description, class: 'form-control', rows: 2, required: true %>
          <div id="emailHelp" class="form-text">Opisz, o czym jest Twój film. Dodaj wszelkie informacje, które mogą zainteresować widzów i zachęcić ich do obejrzenia.</div>
        </div>
      
        <div class="form-group" style="margin-top:10px">
        <%= form.label :uploaded_video, "Wybierz plik", class: "btn", style: "background-color:#5a005a; color:white; box-shadow: 0 10px 30px #FF33AA;", for: 'videoFile' %>
        <%= form.file_field :uploaded_video, required: true, id: 'videoFile', class: 'form-control-file', style: 'display:none' %>
        <span id="file-name" style="margin-left: 10px;">Nie wybrano pliku</span>
      </div>
      
        <%= form.submit 'Wyślij', class: 'btn', style: 'margin-top:10px; background-color:#c94bc9; font-size:20px;' %>
        <% end %> 

      </div>
    </div>
  </div>

  

  <div style="width:40%; float:left; margin: 50px; height: auto; margin-bottom:100px; margin-top:80px; margin-left:70px">
    <%= image_tag("add_movie.jpeg", height: 500, class:"logo", style: "margin-left:30px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);") %>
  </div>
</div>

<footer>
  <p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>

<script>
  document.getElementById('videoFile').addEventListener('change', function(event) {
    const fileNameElement = document.getElementById('file-name');
    const fileName = event.target.files.length ? event.target.files[0].name : 'Nie wybrano pliku';
    fileNameElement.textContent = fileName;
  });
</script>

app/views/videos/show.html.erb
<nav class="navbar navbar-expand-lg fixed-top" style="box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15); ">
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= image_tag("navbar.png", alt: "Logo",  width: 40, height: 40) %>
    <b><span style="padding-top:40px">ClipCentral</span></b>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
  </div>
</div>
</nav>


<div id="cont" style="margin-top:30px" class="page-transition">


<div style="width:40%; float:left; margin: 50px; height:auto; margin-bottom:30px; height:600px">
<center>
<h2><span class="badge pill" style="background-color:#5a005a; font-size:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);"><%= @video.title %></span><span class="badge pill text-bg-light" style=" font-size:11px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); margin-left:5px;">  <%= @video.created_at %></span></h2>
<p><%= @video.description %></p>
<video width="50%" controls style="border-radius:20px; border: 3px solid #c94bc9; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
  <source src="<%= rails_blob_path(@video.uploaded_video, only_path: true) %>" type="video/mp4">
  Twoja przeglądarka nie wspiera elementu wideo.
</video>


</center>
</div>

<div style="width:40%; float:left; margin: 50px; background-color:#C2DFFF; padding:10px; border-radius:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); position: relative; height: 610px; display: flex; flex-direction: column; justify-content: space-between;">


<!-- Sekcja Komentarze -->
<div style="flex-grow: 1; overflow-y: auto;">
<div style="display: flex; justify-content: space-between; align-items: center;">
<h2><span class="badge pill" style="background-color:#5a005a; font-size:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Komentarze 💬</span></h2>

<% if current_user.premium? %>
  <%= link_to 'Pobierz film 📥', download_video_path(@video), method: :get, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
<% end %>

<% if current_user.admin? && @video.reports.any? %>
  <%= button_to '❌ Usuń film', video_path(@video), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć ten film?' }, class: 'btn btn-danger', style: 'font-weight:600; font-size:16px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);'%>
<% end %>
</div>
  <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  
  <div id="comments-list">
    <% @comments.each do |comment| %>
      <div class="comment mt-2 d-flex align-items-center">
        <strong style="margin-right:5px"><%= comment.user.name %>: </strong> <%= comment.content %>
        <% if current_user.admin? %>
          <%= button_to '❌', video_comment_path(@video, comment), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć ten komentarz?' }, class: 'btn btn-sm' %>
        <% end %>
      </div>
    <% end %>
  </div>

  <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  
  
  
  <% if current_user.premium? || current_user.standard? %>
    <%= form_with(model: [@video, @comment], local: true) do |form| %>
      <div class="form-group d-flex align-items-center">
        <%= form.text_area :content, class: 'form-control', placeholder: 'Dodaj komentarz...', rows: 1, style: "width:86%" %>
        <%= form.submit 'Wyślij', class: 'btn', style:'margin-left:5px; background-color: #ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); float:right' %>
      </div>
    <% end %>
  <% end %>
</div>

<% if current_user.admin? && @video.reports.any? %>
  <h2><span class="badge pill" style="background-color:#5a005a; font-size:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Zgłoszenia tego filmu 🚨</span></h2>
  <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  
  <div style="max-height: 300px; overflow-y: auto; padding-right: 10px;">
    <% @video.reports.each do |report| %>
      <div class="report mt-2 d-flex align-items-center justify-content-between" style="border: 1px solid #c94bc9; padding: 10px; border-radius: 10px; background-color: #ffcde3; margin-bottom:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
        <div>
          <strong>Zgłoszone przez:</strong> <%= report.user.name %><br>
          <strong>Powód:</strong> <%= report.reason %>
        </div>
        <div>
          <%= button_to '❌ Usuń zgłoszenie', video_report_path(report.video, report), method: :delete, class: 'btn btn-danger', data: { confirm: 'Czy na pewno chcesz usunąć to zgłoszenie?' } %>
        </div>
      </div>
      <hr style="border: 2px solid; color: #c94bc9; width:100%; margin-top:10px">
    <% end %>
  </div>
<% end %>


<!-- Sekcja Zgłoszenie Filmu -->
<% if (current_user.premium? || current_user.standard?) && @video.user != current_user %>
  <% if @video.reports.exists?(user: current_user) %>
  <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  <h2><span class="badge pill" style="background-color:#5a005a; font-size:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Zgłoszenie filmu 🚨</span></h2>
    <p style="color:#c3195d">Już zgłosiłeś ten film. Nie możesz kilka razy zgłosić tego samego filmu.</p>
  <% else %>
    <hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
    <div>
      <h2><span class="badge pill" style="background-color:#5a005a; font-size:20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">Zgłoszenie filmu 🚨</span></h2>
      <%= form_with(model: [@video, @report], local: true) do |form| %>
        <div class="form-group d-flex align-items-center">
          <%= form.text_area :reason, class: 'form-control', rows: 1, placeholder: 'Podaj powód zgłoszenia filmu...', style:'width:86%' %>
          <%= form.submit 'Wyślij', class: 'btn', style:'margin-left:5px; background-color: #ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>



<!-- Przyciski do powrotu -->
  <% if current_user.premium? %>
<hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  <div class="btn-group mt-1" role="group">
    <%= link_to 'Powróć do przeglądania filmów 🔍', pind_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
    <%= link_to 'Przeglądaj swoje filmy 👨🏻‍💼', profp_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
  </div>
<% elsif current_user.admin? %>
  <div class="btn-group mt-1" role="group">
    <%= link_to 'Powróć do przeglądania filmów 🔍', all_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
    <%= link_to 'Powróć do zgłoszeń 🚨', rep_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
      </div>
<% else %>
<hr style="border: 2px solid; color: #ff69b4; width:100%; margin-top:10px">
  <div class="btn-group mt-1" role="group">
    <%= link_to 'Powróć do przeglądania filmów 🔍', uind_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
    <%= link_to 'Przeglądaj swoje filmy 👨🏻‍💼', prof_path, class: 'btn', style:'background-color:#ff69b4; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);' %>
  </div>
<% end %>


  
</div>

</div>
</div>

<footer>
<p><b>Copyright &copy 2024 </b> ClipCentral. Wszelkie prawa zastrzeżone.</p>
</footer>